version: "3.1"

networks:
  shared-cudos-network:
    name: shared-cudos-network

volumes:
  cudosallowlistdbdata:
    driver: local

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  cudos-allowlist:
    image: cudos-allowlist
    container_name: cudos-allowlist
    build:
      dockerfile: docker/docker.dockerfile
      context: ../
      args:
        args:
        USER_ID: "$USER_ID"
        USER_NAME: "$USER_NAME"
        GROUP_ID: "$GROUP_ID"
        GROUP_NAME: "$GROUP_NAME"
    restart: unless-stopped
    volumes:
      - "../:/usr/cudos-allowlist"
    ports:
      - "$HOST_PORT:$DOCKER_PORT"
    networks:
      - shared-cudos-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "1"
    depends_on:
      - postgres
    links:
    - postgres
